;; drush make file for johnson in Drupal 6 aka management
;;

; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.33"

; Modules
projects[admin_menu][version] = "1.8"
projects[advanced_help][version] = "1.2"
projects[ajaxblocks][version] = "1.8"
projects[backup_migrate][version] = "2.8"
projects[cck][version] = "2.9"
projects[content_taxonomy][version] = "1.0-rc2"
projects[ctools][version] = "1.11"
projects[date][version] = "2.10"
projects[devel][version] = "1.28"
projects[extlink][version] = "1.17"
projects[filefield][version] = "3.13"
projects[google_analytics][version] = "3.6"
projects[google_cse][version] = "1.2"
projects[google_cse][patch][] = "http://drupal.org/files/1345218.patch"
projects[image][version] = "1.2"
projects[imagefield][version] = "3.11"
projects[imagepicker][version] = "2.16"
projects[insert_view][version] = "2.0"
projects[jquery_ui][version] = "1.5"
projects[link][version] = "2.11"
projects[linkchecker][version] = "2.8"
projects[menu_breadcrumb][version] = "1.4"
projects[menu_clone][version] = "1.0"
projects[mollom][version] = "2.11"
projects[mostpopular][version] = "1.0"
projects[node_import][version] = "1.2"
projects[quicktabs][version] = "2.2"
projects[site_map][version] = "2.2"
projects[tagadelic_views][version] = "1.2"
projects[tagadelic][version] = "1.5"
projects[taxonomy_manager][version] = "2.3"
projects[taxonomy_redirect][version] = "1.3"
projects[token][version] = "1.19"
projects[views_accordion][version] = "1.5"
projects[views_bulk_operations][version] = "1.16"
projects[views_customfield][version] = "1.0"
projects[views_data_export] = "2.0-beta7"
projects[views][version] = "2.16"
projects[webform][version] = "3.21"
projects[wysiwyg][version] = "2.4"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ares][download][type] = "svn"
projects[ares][download][url] =
  "https://svn.library.cornell.edu/ares/trunk/module"

projects[ares][type] = "module"
projects[ares][revision] = "HEAD"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cul_common][type] = "module"
projects[cul_common][download][type] = "svn"
projects[cul_common][download][url] =
  "https://svn.library.cornell.edu/cul_common/trunk/module"
projects[cul_common][revision] = "HEAD"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cul_login][type] = "module"
projects[cul_login][download][type] = "svn"
projects[cul_login][download][url] =
  "https://svn.library.cornell.edu/cul_login/trunk/module"

projects[cul_login][revision] = "HEAD"
projects[cul_login][subdir] = "custom"

projects[cu_customsearch][download][type] = "svn"
projects[cu_customsearch][download][url] = "https://svn.library.cornell.edu/cu_customsearch/trunk/module"
projects[cu_customsearch][type] = "module"
projects[cu_customsearch][subdir] = "custom"
projects[cu_customsearch][revision] = "HEAD"

; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[management_library][download][type] = "svn"
projects[management_library][download][url] =
 "https://svn.library.cornell.edu/management_library/trunk/theme"
projects[management_library][type] = "theme"


;Libraries
libraries[tinymce][download][type] = "svn"
libraries[tinymce][download][url] = "https://svn.library.cornell.edu/tinymce-clone/trunk"
libraries[tinymce][directory_name] = "tinymce"

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery-ui-1.8.16.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[jquery_ui][destination] = "modules/jquery_ui"
